# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=2)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('gene', models.CharField(db_index=True, max_length=255)),
                ('transcript', models.CharField(db_index=True, max_length=255)),
                ('cds_exon', models.PositiveIntegerField()),
                ('number_of_baits', models.PositiveIntegerField()),
                ('bases_covered_by_baits', models.PositiveIntegerField()),
                ('number_of_bases_in_region', models.PositiveIntegerField()),
                ('pct_bases_covered_by_baits', models.DecimalField(db_index=True, decimal_places=3, max_digits=10)),
                ('avg_mapping_quality', models.DecimalField(blank=True, db_index=True, decimal_places=3, max_digits=10, null=True)),
                ('min_mapping_quality', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_mapping_quality', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('avg_coverage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('min_coverage', models.DecimalField(db_index=True, decimal_places=3, max_digits=10)),
                ('max_coverage', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'verbose_name': 'Quality Stat',
                'verbose_name_plural': 'Quality Stats',
            },
        ),
    ]
