---
- name: Get NGINX 1.10
  yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    state: installed
  become: true

- name: Install nginx
  yum: name=nginx state=installed
  become: true

- name: Create Debian style NGINX directories
  file: path=/etc/nginx/{{ item }} state=directory mode=0744
  with_items:
    - sites-available
    - sites-enabled
  become: true

- name: Create Nginx logs directory
  file: path={{ project_home }}/logs/nginx owner={{ svc_user }} group={{ svc_group }} state=directory mode=0777
  become: true

- name: Copy nginx configuration
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'nginx.conf', dest: '/etc/nginx/nginx.conf' }
    - { src: 'default.conf', dest: '/etc/nginx/sites-available/default.conf' }
    - { src: 'exomeslicer.conf.j2', dest: '/etc/nginx/sites-available/exomeslicer.conf' }
  become: true

- name: Enable ExomeSlicer
  file: src=/etc/nginx/sites-available/exomeslicer.conf dest=/etc/nginx/sites-enabled/exomeslicer.conf state=link mode=0744
  become: true

- name: Enable HTTP rule for NGINX
  firewalld: service={{ item }} permanent=true state=enabled
  with_items:
    - http
    - https
  become: true

- name: Create NGINX user
  user: name=nginx group={{ svc_group }} comment=NGINXUser shell=/sbin/nologin createhome=no
  become: true

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  become: true

- name: restart firewalld
  service: name=firewalld state=restarted enabled=yes
  become: true
