---
# This playbook will install all common dependencies for a RHEL7 app server

- name: Update RHEL7 yum
  yum: name=* state=latest skip_broken=yes
  become: true

- name: Install RHEL7 packages
  yum: name={{ item }} state=installed
  with_items:
    - epel-release
    - htop
    - nano
    - iptables-services
    - lsof
    - telnet-server
    - "@Development Tools"
    - python-devel
    - libffi-devel
    - zlib-devel
    - bzip2
    - bzip2-devel
    - readline-devel
    - sqlite
    - sqlite-devel
    - openssl-devel
    - gcc
  become: true

- name: Copy ExomeSlicer service files and environment file
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: exomeslicer.service.j2, dest: /usr/lib/systemd/system/exomeslicer.service }
    - { src: env.j2, dest: /etc/sysconfig/exomeslicer }
  become: true
